name: CI Build

on:
  push: { }
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
      - name: Prepare Google Services
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > app/google-services.json
      - name: Prepare Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew assembleDevelopmentDebug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Development Debug APK
          path: app/build/outputs/apk/development/debug/*.apk
      - name: Unit Tests
        run: ./gradlew testDevelopmentDebugUnitTest
      - name: Unit Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: app/build/test-results/testDevelopmentDebugUnitTest/TEST-*.xml
      - name: Upload Unit Test Results for Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-results
          path: app/build/test-results/testDevelopmentDebugUnitTest/TEST-*.xml
      - name: Lint
        run: ./gradlew lintDevelopmentDebug
      - name: Build
        run: ./gradlew assembleDevelopmentDebugAndroidTest
      - name: Upload Instrumentation APK
        uses: actions/upload-artifact@v3
        with:
          name: Development Debug AndroidTest APK
          path: app/build/outputs/apk/androidTest/development/debug/*.apk
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Instrumentation Tests
        run: gcloud firebase test android run --app app/build/outputs/apk/development/debug/*.apk --test app/build/outputs/apk/androidTest/development/debug/*.apk --results-dir ${{github.repository}}-${{github.run_number}}-${{github.run_attempt}}
